---
- name: main
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
  - name: create bucket
    terraform:
      project_path: terraform/
      force_init: true
      lock: true
      state: present
  - name: upload file
    aws_s3:
      bucket: ansible-terraform
      object: file.txt
      src: file.txt
      mode: put
